version: '3'
services:
  postgres:
    image: postgis/postgis:13-3.2
    environment:
      POSTGRES_DB: django
      POSTGRES_PASSWORD: postgres
    ports:
      - ${DOCKER_POSTGRES_PORT-5432}:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.9.13-management
    ports:
      - ${DOCKER_RABBITMQ_PORT-5672}:5672

  minio:
    image: bitnami/minio:2022.3.5-debian-10-r3
    # When run with a TTY, minio prints credentials on startup
    tty: true
    command: ["server", "/data"]
    environment:
      MINIO_ROOT_USER: minioAccessKey
      MINIO_ROOT_PASSWORD: minioSecretKey
    ports:
      - ${DOCKER_MINIO_PORT-9000}:9000
    volumes:
      - fsdata:/data

volumes:
  dbdata:
  fsdata:
