name: ci
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:13-3.2
        env:
          POSTGRES_DB: django
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
      rabbitmq:
        image: rabbitmq:3.9.13-management
        ports:
          - 5672:5672
      minio:
        # This image does not require any command arguments (which GitHub Actions don't support)
        image: bitnami/minio:2022.3.5-debian-10-r3
        env:
          MINIO_ROOT_USER: minioAccessKey
          MINIO_ROOT_PASSWORD: minioSecretKey
        ports:
          - 9000:9000
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install ffmpeg
        run: |
          sudo apt update
          sudo apt-get install --no-install-recommends --yes ffmpeg
      - name: Install tox and codecov
        run: |
          pip install --upgrade pip
          pip install tox codecov
      - name: Run linting
        run: |
          tox -e lint
        env:
          DJANGO_DATABASE_URL: postgres://postgres:postgres@localhost:5432/django
          DJANGO_MINIO_STORAGE_ENDPOINT: localhost:9000
          DJANGO_MINIO_STORAGE_ACCESS_KEY: minioAccessKey
          DJANGO_MINIO_STORAGE_SECRET_KEY: minioSecretKey
      - name: Run check migrations
        run: |
          tox -e check-migrations
        env:
          DJANGO_DATABASE_URL: postgres://postgres:postgres@localhost:5432/django
          DJANGO_MINIO_STORAGE_ENDPOINT: localhost:9000
          DJANGO_MINIO_STORAGE_ACCESS_KEY: minioAccessKey
          DJANGO_MINIO_STORAGE_SECRET_KEY: minioSecretKey
      # - name: Run tests
      #   run: |
      #     tox -e test
      #   env:
      #     DJANGO_DATABASE_URL: postgres://postgres:postgres@localhost:5432/django
      #     DJANGO_MINIO_STORAGE_ENDPOINT: localhost:9000
      #     DJANGO_MINIO_STORAGE_ACCESS_KEY: minioAccessKey
      #     DJANGO_MINIO_STORAGE_SECRET_KEY: minioSecretKey
      # - name: Upload Coverage
      #   run: |
      #     codecov
